#!/bin/python
#
# $Header: langchain_tools.py 12-jun-2026.06:33:35 tanisaga Exp $
#
# langchain_tools.py
#
# Copyright (c) 2026, Oracle and/or its affiliates.
#
#    NAME
#      langchain_tools.py - LangChain tool definitions
#
#    DESCRIPTION
#      Defines database tools and helper functions used
#      by the OCI IAM LangChain demo.
#
#    NOTES
#      <other useful comments, qualifications, etc.>
#
#    MODIFIED   (MM/DD/YY)
#    tanisaga    06/12/26 - Creation
#

from langchain_core.tools import tool

# Allowed HR table for query access
HR_TABLE = "HR.EMPLOYEES"


def get_username(conn) -> str:
    """
    Return authenticated end-user identity.
    """

    with conn.cursor() as cursor:

        cursor.execute(
            "select ORA_END_USER_CONTEXT.username "
            "from sys.dual"
        )

        row = cursor.fetchone()

        return row[0] if row else "unknown"


def build_system_prompt(user: str) -> str:
    """
    Build system instructions for the HR assistant.
    """

    return f"""
You are an Oracle HR assistant.

Authenticated user: {user}

Rules:
- Use only SELECT queries.
- Prefix table name with "HR."
- Always inspect schema before querying.
- Never assume column names.
- Use only HR.EMPLOYEES.
- When the user asks about themselves,
  use ORA_END_USER_CONTEXT.USERNAME.
- Match employee records where
  EMAIL = ORA_END_USER_CONTEXT.USERNAME.
- Return responses in plain English.
- Do not expose SQL queries unless requested.
""".strip()


def _format_query_result(cursor, rows) -> str:
    """
    Convert query results into readable text.
    """

    # Extract column names
    headers = [col[0] for col in cursor.description]

    lines = [" | ".join(headers)]

    # Format each row
    for row in rows:

        formatted_row = [
            "NULL" if value is None else str(value)
            for value in row
        ]

        lines.append(" | ".join(formatted_row))

    return "\n".join(lines)


def create_tools(conn):

    @tool
    def list_tables() -> str:
        """
        List available HR tables.
        """

        return f"Tables: {HR_TABLE}"

    @tool
    # End user has access to the table.
    # So it is able to fetch the table description.
    def describe_table(table_name: str) -> str:
        """
        Return table column names.
        """

        try:
            with conn.cursor() as cursor:

                # Fetch only schema metadata
                cursor.execute(
                    f"SELECT * FROM {table_name} "
                    "WHERE 1=0"
                )

                # Extract column names
                columns = [
                    desc[0]
                    for desc in cursor.description
                ]

                return (
                    f"Table {table_name} columns: "
                    + ", ".join(columns)
                )

        except Exception as exc:

            return (
                f"ERROR fetching schema: {exc}"
            )

    @tool
    def execute_sql(query: str) -> str:
        """
        Execute SQL query generated by the agent.
        """

        clean_query = (
            query.replace("```sql", "")
            .replace("```", "")
            .strip()
            .rstrip(";")
        )

        try:
            with conn.cursor() as cursor:

                cursor.execute(clean_query)

                rows = cursor.fetchall()

                if not rows:
                    return "NO_DATA_FOUND"

                return _format_query_result(
                    cursor,
                    rows,
                )

        except Exception as exc:

            return f"DATABASE_ERROR: {exc}"

    # Register tools
    tools = [
        list_tables,
        describe_table,
        execute_sql,
    ]

    # Tool lookup map
    tool_map = {
        "list_tables":
            list_tables,

        "describe_table":
            describe_table,

        "execute_sql":
            execute_sql,
    }

    return tools, tool_map