
###############################################
# OCI IAM settings to fetch OAuth2 access token
###############################################

[iam_domain_default]

iam_domain_url=https://idcs-****.identity.oraclecloud.com:443
iam_token_url=https://idcs-*****.identity.oraclecloud.com:443/oauth2/v1/token

dbapp_application_id=6****c

dbapp_client_id=7******0
dbapp_client_secret=idcscs-******

midtapp_client_id=3*****7
midtapp_client_secret=idcscs-****7

clientapp_client_id=3****b
clientapp_client_secret=idcscs-5******3

midtier_scope=LangchainAgentLangchainAgent_ACCESS

db_scope=OracleDBDB_ACCESS_SCOPE


#################################################
# Username,password is used to fetch OAuth2 token
# User OCI is used to fetch PoP DB token
#################################################
[iam_user1]
domain = iam_domain_default
username = EmmaBaker
password = *****

[iam_user2]
domain = iam_domain_default
username = MarvinGreenberg
password = ******