-- Content domain: normalized relational tables + a JSON Relational Duality View.
-- Auto-runs on first DB startup (this folder is mounted into container-entrypoint-initdb.d).
--
-- The point for the video: data is stored NORMALIZED (clean, governed, joinable) but the app
-- reads/writes it as a single JSON "post" document. No ORM, no dual-write, no sync code.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE platforms (
  platform_id   VARCHAR2(20) PRIMARY KEY,            -- 'instagram','linkedin','tiktok',...
  display_name  VARCHAR2(60) NOT NULL
);

CREATE TABLE brands (
  brand_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(200) NOT NULL,
  contact    VARCHAR2(200)
);

CREATE TABLE deals (
  deal_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id   NUMBER NOT NULL REFERENCES brands(brand_id),
  status     VARCHAR2(20) DEFAULT 'lead' NOT NULL,   -- lead|negotiating|signed|delivered
  fee_usd    NUMBER(12,2),
  due_date   DATE
);

CREATE TABLE posts (
  post_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_id   VARCHAR2(20) NOT NULL REFERENCES platforms(platform_id),
  brand_id      NUMBER REFERENCES brands(brand_id),     -- nullable: not every post is sponsored
  kind          VARCHAR2(20) DEFAULT 'post' NOT NULL,   -- post|reel|video|article|tweet|episode
  title         VARCHAR2(1000),                          -- videos/articles have titles
  caption       CLOB,                                    -- caption / description / body text
  url           VARCHAR2(1000),
  published_at  TIMESTAMP,
  likes         NUMBER DEFAULT 0,
  comments      NUMBER DEFAULT 0,
  views         NUMBER DEFAULT 0,
  sponsored     NUMBER(1) DEFAULT 0,                     -- paid partnership? (authoritative from Notion)
  brand         VARCHAR2(200),                            -- brand, for sponsored items
  visibility    VARCHAR2(12) DEFAULT 'content' NOT NULL,  -- 'content' (searched) | 'business' (private) | 'archived' (off-topic); only 'content' is searched/wiki'd/consolidated
  series        VARCHAR2(20),                             -- optional content series, e.g. 'tech_walk' (walking interviews with a guest)
  content_embedding VECTOR(384, FLOAT32)                 -- semantic search over the content (in-DB MiniLM)
);

CREATE TABLE media (
  media_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id   NUMBER NOT NULL REFERENCES posts(post_id),
  kind      VARCHAR2(20) NOT NULL,    -- image|video|audio
  url       VARCHAR2(1000) NOT NULL   -- REFERENCE only; binaries live in object storage, never the DB
);

-- ── JSON Relational Duality View ─────────────────────────────────────────────
-- One "post" served as a document that nests its platform, brand, and media[].
-- @insert/@update/@delete annotations make it fully read-write through the view.
-- Note: the GraphQL-style duality syntax separates fields by WHITESPACE (not commas),
-- and nested objects map to JOINED TABLES via FK — you can't group same-table columns
-- into an inline sub-object, so likes/comments/views are top-level here.
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW post_dv AS
  posts @insert @update @delete
  {
    _id         : post_id
    kind        : kind
    caption     : caption
    url         : url
    publishedAt : published_at
    likes       : likes
    comments    : comments
    views       : views
    platform    : platforms @noinsert @noupdate @nodelete { platformId : platform_id  name : display_name }
    brand       : brands    @insert   @update             { brandId    : brand_id     brandName : name }
    media       : media      @insert @update @delete       [ { mediaId : media_id  kind : kind  url : url } ]
  };
