-- ★ THE STAR OF THE DEMO: persistent agent memory.
-- Auto-runs on first DB startup.
--
-- The thesis: agents that forget are toys; agents that remember compound. Here memory is:
--   • RELATIONAL  → outcomes are queryable/auditable with plain SQL (what worked, what failed)
--   • VECTOR      → past experiences are retrievable by MEANING (semantic recall before acting)
-- ...both in ONE engine. That's the reason we're on Oracle 26ai.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

-- EPISODIC MEMORY: one row per thing the agent did, and how it turned out.
CREATE TABLE agent_memory (
  memory_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id       VARCHAR2(40)  NOT NULL,            -- groups the actions of one agent run
  task         VARCHAR2(500) NOT NULL,            -- what it was asked to do
  action       CLOB          NOT NULL,            -- what it decided / did
  tool         VARCHAR2(80),                      -- tool invoked, if any
  outcome      VARCHAR2(10)  NOT NULL,            -- 'success' | 'failure'
  reward       NUMBER(4,3),                       -- optional score 0..1
  detail       CLOB,                              -- result text / the lesson learned
  embedding    VECTOR(384, FLOAT32),              -- set at INSERT via VECTOR_EMBEDDING(MINILM ...)
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  -- Structural privacy, same contract as posts.visibility: a memory whose text trips the
  -- deny-list (deal/fee terms) is written 'business' and every read filters to 'content'.
  visibility   VARCHAR2(12) DEFAULT 'content' NOT NULL,
  CONSTRAINT chk_outcome CHECK (outcome IN ('success','failure'))
);

-- Idempotent for already-created databases (apply_schema.py TOLERATE swallows ORA-01430;
-- on a fresh DB the column is already in the CREATE above, so this ALTER is skipped).
ALTER TABLE agent_memory ADD (visibility VARCHAR2(12) DEFAULT 'content' NOT NULL);

-- NOTE: At demo scale, exact VECTOR_DISTANCE search (no index) is instant and needs no
-- special setup. A fast approximate (HNSW) index is OPTIONAL and only pays off at scale —
-- but it requires a dedicated vector memory pool first. See setup/03_vector_index.sql.

-- THE AUDITABLE FLEX: the agent's track record, as plain SQL over the same memory.
-- ("Show me the agent's success rate per tool" — a vector-only store can't do this.)
CREATE OR REPLACE VIEW tool_stats AS
  SELECT tool,
         COUNT(*)                                                  AS attempts,
         SUM(CASE WHEN outcome = 'success' THEN 1 ELSE 0 END)      AS successes,
         ROUND(AVG(CASE WHEN outcome = 'success' THEN 1 ELSE 0 END), 3) AS success_rate
  FROM   agent_memory
  GROUP  BY tool;
