-- SEMANTIC MEMORY: durable, consolidated facts the agent has learned.
-- Built by an LLM pipeline that distills EPISODIC memory (past research runs) into
-- reusable facts ("the creator's content centers on their core themes..."), so the
-- agent carries knowledge forward instead of re-deriving it every time.
-- (DeepLearning.AI "memory-aware agents": consolidate episodic -> semantic.)

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE semantic_memory (
  fact_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fact        VARCHAR2(1000) NOT NULL,          -- one durable, reusable fact
  category    VARCHAR2(60),                      -- e.g. theme | audience | format | tool
  source      VARCHAR2(40) DEFAULT 'consolidation' NOT NULL,
  embedding   VECTOR(384, FLOAT32),             -- for semantic recall (in-DB MiniLM)
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
