-- PASSAGE-LEVEL detail for long items (chats, transcripts, long articles).
-- Item-level overview/summary lives in `posts`; this holds the full content, chunked and
-- embedded, so semantic search can land on the SPECIFIC passage, not just the topic.
-- (Hierarchical memory best practice: summary index on top, chunk detail underneath.)

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE content_chunks (
  chunk_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     NUMBER NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
  seq         NUMBER NOT NULL,                  -- order within the item
  chunk       CLOB   NOT NULL,                  -- the passage text
  embedding   VECTOR(384, FLOAT32)              -- in-DB MiniLM embedding of the passage
);
