-- PROCEDURAL memory: the agent's tools/skills stored AS memory, so it can retrieve only the
-- RELEVANT tools for a given query at inference time (instead of always loading every tool).
-- Best practice from "memory-aware agents": treat tools as procedural memory, embed their
-- descriptions, and semantic-search them. Scales as the toolset grows.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE procedural_memory (
  tool_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(80)  NOT NULL UNIQUE,
  description CLOB          NOT NULL,
  schema_json CLOB,                              -- the tool's JSON input_schema (NULL for server tools)
  kind        VARCHAR2(20)  DEFAULT 'client' NOT NULL,   -- client | server
  embedding   VECTOR(384, FLOAT32)               -- embedding of name + description
);
