-- KARPATHY WIKI LAYER: LLM-compiled, self-maintaining topic pages over your content.
-- This is the strongest JSON Relational Duality + relational showcase in the brain, because a
-- wiki page is BOTH a document (the page) AND a graph of relationships (links + citations):
--   wiki_pages   = the page  (JSON document + vector)
--   page_links   = page -> page cross-links  (relational, many-to-many graph)
--   page_sources = page -> your content       (relational citations back to posts)
-- A Duality View serves a page as ONE JSON document with its citations nested.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE wiki_pages (
  page_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic      VARCHAR2(200) NOT NULL UNIQUE,
  body       CLOB          NOT NULL,           -- the LLM-compiled synthesis
  embedding  VECTOR(384, FLOAT32),             -- semantic search over the page
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE page_links (
  from_page_id NUMBER NOT NULL REFERENCES wiki_pages(page_id) ON DELETE CASCADE,
  to_page_id   NUMBER NOT NULL REFERENCES wiki_pages(page_id) ON DELETE CASCADE,
  CONSTRAINT page_links_pk PRIMARY KEY (from_page_id, to_page_id)
);

CREATE TABLE page_sources (
  page_id NUMBER NOT NULL REFERENCES wiki_pages(page_id) ON DELETE CASCADE,
  post_id NUMBER NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
  CONSTRAINT page_sources_pk PRIMARY KEY (page_id, post_id)
);

-- High-water mark so `wiki.py --refresh` is cheap: it recompiles only topics whose top
-- retrieval now includes posts newer than the last compile (no new content -> no LLM calls).
CREATE TABLE wiki_meta (
  id               NUMBER DEFAULT 1 PRIMARY KEY,
  last_max_post_id NUMBER DEFAULT 0 NOT NULL,
  refreshed_at     TIMESTAMP DEFAULT SYSTIMESTAMP
);
INSERT INTO wiki_meta (id, last_max_post_id) VALUES (1, 0);

-- A page as one JSON document, with its citations (-> your content) nested.
-- (Cross-links live in page_links and are queried relationally, e.g. "what links to X".)
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW wiki_page_dv AS
  wiki_pages @insert @update @delete
  {
    _id       : page_id
    topic     : topic
    body      : body
    updatedAt : updated_at
    sources   : page_sources @insert @delete
      [ { post : posts @noinsert @noupdate @nodelete
            { postId : post_id  title : title  platform : platform_id  url : url } } ]
  };
