-- ANALYTICS: per-deliverable, per-platform performance for brand collabs, collected from the
-- screenshots you keep for each collaboration (adapt the source to wherever you store them).
-- One row per (brand, deliverable, platform). Numbers only — no contracts/financials.

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE analytics (
  analytics_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand        VARCHAR2(120),
  deliverable  VARCHAR2(400),
  platform     VARCHAR2(40),         -- youtube | instagram | x | linkedin | threads | tiktok ...
  impressions  NUMBER,
  engagements  NUMBER,
  views        NUMBER,
  captured_at  DATE,
  source_url   VARCHAR2(600),         -- the Drive file the number came from
  collected_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
