-- SYNC HEARTBEAT: one row per sync run, written by scripts/sync.py as its last act.
-- This is the difference between "rows changed" (a hint) and "the pipeline RAN" (proof).
-- The hosted status panel reads it to answer, from any device — even when the machine
-- that runs the sync is closed — "is my pipeline alive, and which steps failed last run?"

ALTER SESSION SET CURRENT_SCHEMA = CCC;

CREATE TABLE sync_runs (
  run_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  host       VARCHAR2(80),           -- which machine ran it (hostname)
  ok_steps   NUMBER NOT NULL,
  bad_steps  NUMBER NOT NULL,        -- fail + skip (details in steps_json)
  steps_json CLOB NOT NULL           -- [{"label","status","seconds"}, ...]
);
