resources:
  - service-account.yaml
  - backend.yaml
  - backend-svc.yaml
configMapGenerator:
  - name: backend-properties
    files:
      - application.yaml
  - name: wallet-zip
    files:
      - wallet/wallet.zip
namespace: backend