"""seed.py - load Oracle docs into Oracle AI Database 26ai with in-DB embeddings.

Two-phase setup:
  Phase 1 (as SYSTEM): create a dedicated demo user with the USERS tablespace,
  create the ONNX directory, grant privileges. Required because VECTOR columns
  cannot live in the SYSTEM tablespace (ORA-43853).

  Phase 2 (as the demo user): load the ONNX embedding model, create the chunks
  table, insert the chunks (embeddings generated by VECTOR_EMBEDDING inside
  the database), and build the HNSW index.
"""

import json
import os
import sys
from pathlib import Path

import oracledb
import requests
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

load_dotenv()

# Admin connection (used only for one-time setup of user + directory).
ADMIN_USER = os.getenv("ORACLE_ADMIN_USER", "system")
ADMIN_PASSWORD = os.getenv("ORACLE_ADMIN_PASSWORD", "Welcome12345")

# Demo application user. All RAG data lives in this user's schema.
APP_USER = os.getenv("ORACLE_USER", "raguser")
APP_PASSWORD = os.getenv("ORACLE_PASSWORD", "RagUser_2026")
ORACLE_DSN = os.getenv("ORACLE_DSN", "localhost:1521/FREEPDB1")

DATA_DIR = Path(os.getenv("DATA_DIR", "./data"))
DB_ONNX_DIR = os.getenv("DB_ONNX_DIR", "/opt/oracle/data")

ONNX_MODEL_NAME = "ALL_MINILM_L12_V2"
ONNX_FILE_NAME = "all_MiniLM_L12_v2.onnx"
ONNX_URL = os.getenv(
    "ONNX_URL",
    "https://adwc4pm.objectstorage.us-ashburn-1.oci.customer-oci.com/p/"
    "iPX9W0MZeRkwJKWdFmdJCemmN-iKAl_bFvNGYLW7YqIrw4kKsukL24J2q93Beb9S/n/"
    "adwc4pm/b/OML-ai-models/o/all_MiniLM_L12_v2.onnx",
)
PDF_FILE_NAME = "ai-vector-search-users-guide.pdf"  # legacy, kept for reference

# Documents to ingest into the RAG corpus. Each entry has:
#   - url: the public download URL
#   - filename: where it gets saved locally inside DATA_DIR
#   - source_name: a human-readable label that will be tagged on every chunk
#                  from this document so the UI can show "from: <source_name>"
DOCUMENTS = [
    {
        "url": (
            "https://docs.oracle.com/en/database/oracle/oracle-database/23/"
            "vecse/ai-vector-search-users-guide.pdf"
        ),
        "filename": "ai-vector-search-users-guide.pdf",
        "source_name": "AI Vector Search User's Guide",
    },
    {
        "url": (
            "https://docs.oracle.com/en/database/oracle/oracle-database/23/"
            "adjsn/json-developers-guide.pdf"
        ),
        "filename": "json-developers-guide.pdf",
        "source_name": "JSON Developer's Guide",
    },
    {
        "url": (
            "https://docs.oracle.com/en/database/oracle/oracle-database/23/"
            "cncpt/database-concepts.pdf"
        ),
        "filename": "database-concepts.pdf",
        "source_name": "Database Concepts",
    },
]

CHUNK_SIZE = 2000
CHUNK_OVERLAP = 200

DATA_DIR.mkdir(parents=True, exist_ok=True)


def download_if_missing(url, dest):
    """Download a file with progress, using requests (which uses certifi)."""
    if dest.exists() and dest.stat().st_size > 0:
        size_mb = dest.stat().st_size / (1024 * 1024)
        print(f"  -> {dest.name} already present ({size_mb:.1f} MB), skipping")
        return
    print(f"  -> downloading {dest.name}")
    response = requests.get(url, stream=True, timeout=60)
    response.raise_for_status()
    total = int(response.headers.get("content-length", 0))
    downloaded = 0
    with open(dest, "wb") as fh:
        for chunk in response.iter_content(chunk_size=1024 * 1024):
            if not chunk:
                continue
            fh.write(chunk)
            downloaded += len(chunk)
            if total:
                pct = (downloaded / total) * 100
                print(
                    f"     {downloaded / (1024 * 1024):6.1f} MB / "
                    f"{total / (1024 * 1024):6.1f} MB  ({pct:5.1f}%)",
                    end="\r",
                )
    if total:
        print()
    print(f"  -> saved to {dest}")


# Oracle error codes that mean "the thing you're dropping doesn't exist".
# Different Oracle packages raise different codes for the same condition,
# so we suppress all of them in safe_execute.
_NONEXISTENT_ERROR_CODES = (
    942,    # ORA-00942: table does not exist
    1418,   # ORA-01418: index does not exist
    1918,   # ORA-01918: user does not exist
    4043,   # ORA-04043: object does not exist
    40284,  # ORA-40284: model does not exist (DBMS_VECTOR variant)
    40287,  # ORA-40287: model does not exist (DBMS_DATA_MINING variant)
)


def safe_execute(cursor, sql):
    """Run SQL, suppressing 'does not exist' errors so the script is rerunnable."""
    try:
        cursor.execute(sql)
    except oracledb.DatabaseError as exc:
        (error,) = exc.args
        if error.code not in _NONEXISTENT_ERROR_CODES:
            raise


def setup_user_and_directory(admin_conn):
    """Phase 1: as SYSTEM, drop and recreate the demo user with the USERS
    tablespace, then create the ONNX directory and grant access on it."""
    cursor = admin_conn.cursor()

    # Force-disconnect any existing sessions for the demo user so DROP USER
    # can succeed cleanly. Ignore errors if nothing is connected.
    try:
        cursor.execute(
            f"""
            BEGIN
                FOR s IN (
                    SELECT sid, serial# FROM v$session
                    WHERE username = UPPER('{APP_USER}')
                ) LOOP
                    EXECUTE IMMEDIATE
                        'ALTER SYSTEM KILL SESSION ''' ||
                        s.sid || ',' || s.serial# || ''' IMMEDIATE';
                END LOOP;
            END;
            """
        )
    except oracledb.DatabaseError:
        pass

    # Drop and recreate the user. Drop is suppressed if the user doesn't exist.
    safe_execute(cursor, f"DROP USER {APP_USER} CASCADE")
    cursor.execute(
        f"CREATE USER {APP_USER} IDENTIFIED BY {APP_PASSWORD} "
        f"DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS"
    )

    # Privileges:
    #   CONNECT, RESOURCE: basic schema usage
    #   DB_DEVELOPER_ROLE: bundles common developer privileges (CREATE TABLE, etc.)
    #   CREATE MINING MODEL: required to load the ONNX embedding model
    cursor.execute(
        f"GRANT CONNECT, RESOURCE, DB_DEVELOPER_ROLE, "
        f"CREATE MINING MODEL TO {APP_USER}"
    )

    # Create the directory object that maps to the host path where the ONNX
    # file lives. The Oracle container has /opt/oracle/data mounted from ./data.
    cursor.execute(f"CREATE OR REPLACE DIRECTORY ONNX_DIR AS '{DB_ONNX_DIR}'")
    cursor.execute(f"GRANT READ, WRITE ON DIRECTORY ONNX_DIR TO {APP_USER}")

    admin_conn.commit()
    cursor.close()


def main():
    print(f"Step 1: download embedding model and {len(DOCUMENTS)} document(s)")
    download_if_missing(ONNX_URL, DATA_DIR / ONNX_FILE_NAME)
    for doc in DOCUMENTS:
        download_if_missing(doc["url"], DATA_DIR / doc["filename"])

    print(f"\nStep 2: connect as {ADMIN_USER} to set up the demo user")
    admin_conn = oracledb.connect(
        user=ADMIN_USER, password=ADMIN_PASSWORD, dsn=ORACLE_DSN
    )
    print(f"  -> connected as {ADMIN_USER}")
    setup_user_and_directory(admin_conn)
    print(f"  -> user {APP_USER} ready (USERS tablespace, all needed grants)")
    print(f"  -> directory ONNX_DIR points at {DB_ONNX_DIR}")
    admin_conn.close()

    print(f"\nStep 3: reconnect as {APP_USER} for the rest of the seed")
    connection = oracledb.connect(
        user=APP_USER, password=APP_PASSWORD, dsn=ORACLE_DSN
    )
    cursor = connection.cursor()
    print(f"  -> connected as {APP_USER}")

    print("\nStep 4: load the ONNX model into the database")
    safe_execute(
        cursor,
        f"BEGIN DBMS_VECTOR.DROP_ONNX_MODEL("
        f"model_name => '{ONNX_MODEL_NAME}', force => TRUE); END;",
    )
    cursor.execute(
        f"""
        BEGIN
            DBMS_VECTOR.LOAD_ONNX_MODEL(
                directory  => 'ONNX_DIR',
                file_name  => '{ONNX_FILE_NAME}',
                model_name => '{ONNX_MODEL_NAME}'
            );
        END;
        """
    )
    print(f"  -> model {ONNX_MODEL_NAME} loaded")

    print("\nStep 5: create DOC_CHUNKS table")
    safe_execute(cursor, "DROP INDEX DOC_CHUNKS_VEC_IDX")
    safe_execute(cursor, "DROP INDEX DOC_CHUNKS_HNSW_IDX")  # legacy from earlier runs
    safe_execute(cursor, "DROP TABLE DOC_CHUNKS")
    # Schema matches LangChain OracleVS conventions: ID, TEXT, METADATA, EMBEDDING.
    # METADATA uses Oracle 23ai+ native JSON type so python-oracledb auto-
    # deserializes it into a Python dict on retrieval. (CLOB would come back as
    # a raw string and break OracleVS's metadata parsing.)
    cursor.execute(
        """
        CREATE TABLE DOC_CHUNKS (
            ID         VARCHAR2(64) DEFAULT SYS_GUID() PRIMARY KEY,
            TEXT       CLOB,
            METADATA   JSON,
            EMBEDDING  VECTOR(384, FLOAT32)
        )
        """
    )
    print("  -> table DOC_CHUNKS ready in USERS tablespace")

    print(f"\nStep 6: read and chunk {len(DOCUMENTS)} document(s)")
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP
    )
    chunks = []
    for doc in DOCUMENTS:
        loader = PyPDFLoader(str(DATA_DIR / doc["filename"]))
        pages = loader.load()
        doc_chunks = splitter.split_documents(pages)
        # Tag every chunk from this document with its source name so the UI
        # can show "from: <source_name>" and so we can filter by source if needed.
        for chunk in doc_chunks:
            chunk.metadata["source_name"] = doc["source_name"]
        chunks.extend(doc_chunks)
        print(f"  -> {doc['source_name']}: {len(doc_chunks)} chunks")
    print(f"  -> total: {len(chunks)} chunks across {len(DOCUMENTS)} document(s)")

    print("\nStep 7: insert chunks (embeddings generated in the database)")
    insert_sql = """
        INSERT INTO DOC_CHUNKS (TEXT, METADATA, EMBEDDING)
        VALUES (
            :text,
            JSON(:metadata),
            VECTOR_EMBEDDING(ALL_MINILM_L12_V2 USING :text AS data)
        )
    """

    # Build the full list of bind parameters once, then use executemany() to
    # send everything in a single round trip. This is roughly 5-10x faster than
    # cursor.execute() in a loop because we avoid the per-row network latency.
    rows = [
        {
            "text": chunk.page_content,
            "metadata": json.dumps(
                {
                    "source_name": chunk.metadata.get("source_name", "unknown"),
                    "source_page": int(chunk.metadata.get("page", 0)),
                }
            ),
        }
        for chunk in chunks
    ]

    # Insert in batches of 200 so the progress indicator updates a few times
    # for very large document sets, while keeping each batch fast.
    BATCH_SIZE = 200
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        cursor.executemany(insert_sql, batch)
        print(f"  -> inserted {min(i + BATCH_SIZE, len(rows))} / {len(rows)} chunks")

    connection.commit()
    print(f"  -> all {len(rows)} chunks inserted")

    print("\nStep 8: build vector index")
    safe_execute(cursor, "DROP INDEX DOC_CHUNKS_VEC_IDX")
    safe_execute(cursor, "DROP INDEX DOC_CHUNKS_HNSW_IDX")  # legacy name from earlier runs

    # Try HNSW first (in-memory, fast). If the database's VECTOR_MEMORY_SIZE
    # isn't configured for HNSW (ORA-51962), fall back to IVF, which uses
    # regular tablespace storage and works without any memory config.
    # Both index types serve VECTOR_DISTANCE() queries the same way from the
    # application's perspective; the difference is internal storage.
    try:
        cursor.execute(
            """
            CREATE VECTOR INDEX DOC_CHUNKS_VEC_IDX
            ON DOC_CHUNKS (embedding)
            ORGANIZATION INMEMORY NEIGHBOR GRAPH
            DISTANCE COSINE
            WITH TARGET ACCURACY 95
            """
        )
        print("  -> HNSW vector index DOC_CHUNKS_VEC_IDX created (in-memory)")
    except oracledb.DatabaseError as exc:
        (error,) = exc.args
        if error.code == 51962:
            print("  -> VECTOR_MEMORY_SIZE is not configured for HNSW")
            print("     Falling back to IVF index (uses regular tablespace storage)")
            print("     For HNSW in production, set VECTOR_MEMORY_SIZE >= 512M in your DB")
            cursor.execute(
                """
                CREATE VECTOR INDEX DOC_CHUNKS_VEC_IDX
                ON DOC_CHUNKS (embedding)
                ORGANIZATION NEIGHBOR PARTITIONS
                DISTANCE COSINE
                WITH TARGET ACCURACY 95
                """
            )
            print("  -> IVF vector index DOC_CHUNKS_VEC_IDX created")
        else:
            raise

    cursor.close()
    connection.close()
    print(f"\nDone. Make sure your .env has ORACLE_USER={APP_USER}, then run:")
    print("  streamlit run app.py")


if __name__ == "__main__":
    try:
        main()
    except oracledb.DatabaseError as exc:
        print(f"\nDatabase error: {exc}", file=sys.stderr)
        sys.exit(1)
    except requests.exceptions.RequestException as exc:
        print(f"\nDownload error: {exc}", file=sys.stderr)
        sys.exit(1)
