WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT === Mining models ===
SELECT MODEL_NAME FROM USER_MINING_MODELS;

PROMPT === Hybrid index status ===
SELECT INDEX_NAME, DOMIDX_OPSTATUS FROM USER_INDEXES WHERE INDEX_NAME = 'POLICY_HYBRID_IDX';

PROMPT === Policy docs row count ===
SELECT COUNT(*) AS policy_doc_count FROM POLICY_DOCS;

EXIT;
