/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UploadRouteImport } from "./routes/upload";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocumentsIndexRouteImport } from "./routes/documents.index";
import { Route as DocumentsIdRouteImport } from "./routes/documents.$id";

const UploadRoute = UploadRouteImport.update({
  id: "/upload",
  path: "/upload",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: "/documents/",
  path: "/documents/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: "/documents/$id",
  path: "/documents/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/upload": typeof UploadRoute;
  "/documents/$id": typeof DocumentsIdRoute;
  "/documents/": typeof DocumentsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/upload": typeof UploadRoute;
  "/documents/$id": typeof DocumentsIdRoute;
  "/documents": typeof DocumentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/upload": typeof UploadRoute;
  "/documents/$id": typeof DocumentsIdRoute;
  "/documents/": typeof DocumentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/upload" | "/documents/$id" | "/documents/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/upload" | "/documents/$id" | "/documents";
  id: "__root__" | "/" | "/upload" | "/documents/$id" | "/documents/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  UploadRoute: typeof UploadRoute;
  DocumentsIdRoute: typeof DocumentsIdRoute;
  DocumentsIndexRoute: typeof DocumentsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/upload": {
      id: "/upload";
      path: "/upload";
      fullPath: "/upload";
      preLoaderRoute: typeof UploadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/documents/": {
      id: "/documents/";
      path: "/documents";
      fullPath: "/documents/";
      preLoaderRoute: typeof DocumentsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/documents/$id": {
      id: "/documents/$id";
      path: "/documents/$id";
      fullPath: "/documents/$id";
      preLoaderRoute: typeof DocumentsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
