import os
from dotenv import load_dotenv

load_dotenv(override=True)

ORACLE_VECDB_REST_URL = os.getenv("VECDB_REST_URL")
ORACLE_VECDB_USERNAME = os.getenv("VECDB_USERNAME")
ORACLE_VECDB_PASSWORD = os.getenv("VECDB_PASSWORD")
ORACLE_VECDB_ACCESS_TOKEN = os.getenv("VECDB_ACCESS_TOKEN")

ORACLE_TABLE_NAME = os.getenv("ORACLE_TABLE_NAME", "LANGCHAIN_CODE_SEARCH")
ORACLE_VECTOR_DIM = int(os.getenv("ORACLE_VECTOR_DIM", "768"))
ORACLE_DISTANCE_METRIC = os.getenv("ORACLE_DISTANCE_METRIC", "cosine")
